/* prettier-ignore-start */

/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file is auto-generated by TanStack Router
// Import Routes
import { Route as rootRoute } from './routes/__root';
import { Route as IndexImport } from './routes/index';
import { Route as PageImport } from './routes/page';

// Create/Update Routes

const PageRoute = PageImport.update({
  path: '/page',
  getParentRoute: () => rootRoute
} as any);

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/page': {
      id: '/page';
      path: '/page';
      fullPath: '/page';
      preLoaderRoute: typeof PageImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({ IndexRoute, PageRoute });

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/page"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/page": {
      "filePath": "page.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
